name: tasks_flutter_app
description: "Tasks flutter app."
version: 0.1.0

environment:
    sdk: ^3.5.3

dependencies:
    flutter:
        sdk: flutter

    flutter_localizations:
        sdk: flutter

    provider: ^6.0.0
    shared_preferences: ^2.0.15
    intl: ^0.19.0
    http: ^0.13.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    flutter_launcher_icons: ^0.10.0

flutter:
    uses-material-design: true

    assets:
        - assets/lang/en.json
        - assets/lang/ru.json

flutter_icons:
    android: true
    ios: true
    linux: true
    macos: true
    windows: true
    web: true
    image_path: "assets/icons/app_icon.png"
